#!/bin/sh

get_values() {

    case "$1" in
        "percent") [ "$2" = "muted" ] && echo "0" || echo "$2";;
        "icon") [ "$2" = "muted" ] && echo "󰝟" || echo "$(get_icon $2)";;

    esac

}

get_icon() {

    volume_percent=$(echo "$1" | sed 's/%//')

    if [ $volume_percent -le 33 ]; then
        echo "󰕿"

    elif [ $volume_percent -le 66 ]; then
        echo "󰖀"

    else
        echo "󰕾"

    fi

}

volume=$(pamixer --get-volume-human)
val=$(get_values "$1" $volume)
val=$(echo "$val" | sed 's/%//')
echo "$val"

pactl subscribe | while read -r line; do

    state=$(echo "$line" | grep -o 'sink')

    if [ "$state" = "sink" ]; then
        volume=$(pamixer --get-volume-human)
        val=$(get_values "$1" $volume)
        val=$(echo "$val" | sed 's/%//')
        echo "$val"

    fi

done
