#!/bin/sh

get_signal_strength() {

    echo "$(nmcli -t -f in-use,signal dev wifi | grep '*:' | sed 's/*://g')"

}

get_values() {

    case "$1" in
        "percent") [ -z "$2" ] && echo "0" || echo "$2";;
        "icon") [ -z "$2" ] && echo "󰤮" || echo "$(get_icon $2)";;

    esac

}

get_icon() {

    if [ $1 -le 25 ]; then
        echo "󰤟"

    elif [ $1 -le 50 ]; then
        echo "󰤢"

    elif [ $1 -le 75 ]; then
        echo "󰤥"

    else
        echo "󰤨"

    fi

}

strength=$(get_signal_strength)
val=$(get_values "$1" $strength)
echo "$val"

nmcli monitor | while read -r line; do

    state=$(echo "$line" | grep -o "'connected'\|'disconnected'")

    if [ "$state" = "'connected'" ] || [ "$state" = "'disconnected'" ]; then

        strength=$(get_signal_strength)
        val=$(get_values "$1" $strength)
        echo "$val"

    fi

done
