--enable-features=AcceleratedVideoDecodeLinuxGL,VaapiVideoDecoder,VaapiVideoEncoder,Vulkan,VaapiOnNvidiaGPUs
--disable-features=ExtensionManifestV2Unsupported,ExtensionManifestV2Disabled
--use-vulkan
--use-angle=vulkan
--ignore-gpu-blocklist
--enable-zero-copy
