# Lines configured by zsh-newuser-install
HISTFILE=~/.zsh_history
HISTSIZE=1000
SAVEHIST=1000

setopt autocd
setopt appendhistory
setopt PROMPT_SUBST

bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/$USER/.zshrc'

source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
#source /usr/share/zsh/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh
source ~/.local/share/zsh/plugins/zsh-shift-select/zsh-shift-select.plugin.zsh

bindkey "^[[H" beginning-of-line
bindkey "^[[F" end-of-line
bindkey "^[[3~" delete-char
bindkey "^[[1;5D" backward-word
bindkey "^[[1;5C" forward-word

alias ls='eza --icons --color=auto'
alias ll='ls -lh'
alias cte='chmod 755'
alias grep='grep --color=auto'

preexec() {
	printf "\n"

}

precmd() {

    if [ -z $VIRTUAL_ENV_PROMPT ]; then
        VENV_MODULE="%F{#eeb8cb}\ue0bc%f"

    else
        VENV_MODULE="%F{#eeb8cb}%K{#cac3dc}\ue0bc%f%k%F{#48454e}%K{#cac3dc} \ue73c $VIRTUAL_ENV_PROMPT %f%k%F{#cac3dc}\ue0bc%f"

    fi

    PROMPT=$'\n%F{#33275e}%K{#ccbeff} \uf015 %n@%M %f%k%F{#ccbeff}%K{#eeb8cb}\ue0bc%f%k%F{#492534}%K{#eeb8cb} %(3~|.../%2~|%~) %f%k$(echo -ne $VENV_MODULE) \n%F{000}%K{255} %% %f%k%F{255}\ue0b0%f '

}

if [ -z "$XDG_CURRENT_DESKTOP" ]; then
	export QT_QPA_PLATFORMTHEME=qt6ct

fi

autoload -Uz compinit
compinit
# End of lines added by compinstall
