#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x redshift > /dev/null || redshift -l 1:1 -t 5300:5300 -r -g 0.80 &
polybar main &
polybar misc &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         2
bspc config window_gap          6

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a mpv state=floating

bspc config focused_border_color "#E2E2E5"
bspc config normal_border_color "#312F35"

export QT_QPA_PLATFORMTHEME=qt6ct

~/.config/bspwm/watchers/errwatch &
~/.config/bspwm/watchers/ramwatch &
~/.config/bspwm/watchers/batwatch &
~/.config/bspwm/watchers/swapwatch &
~/.config/bspwm/watchers/usbwatch &
~/.config/bspwm/watchers/musicwatch &

xinput set-prop "$(xinput list | grep Touchpad | grep -o 'id=[^[]*' | sed 's/[^0-9]*//g')" "libinput Tapping Enabled" 1 &
vibrant-cli eDP-1 1.3 &

xsetroot -cursor_name left_ptr &
feh --bg-fill ~/Pictures/wallpapers/is_this_oc.jpg
/usr/lib/polkit-kde-authentication-agent-1 &
picom -b
dunst &
/usr/bin/kdeconnectd &
