#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x redshift > /dev/null || redshift -l 1:1 -t 5000:5000 -r -g 0.80 &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         2
bspc config window_gap          8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a mpv state=floating

bspc config focused_border_color "#AAD291"
bspc config normal_border_color "#312F35"

# compositor
picom -b

# eww daemon and bars
eww daemon &
eww -c ~/.config/eww/main_widget daemon &
eww -c ~/.config/eww/notif daemon &
eww open bar-window &

export QT_QPA_PLATFORMTHEME=qt6ct

# Notification tasks
~/.config/bspwm/watchers/errwatch &
~/.config/bspwm/watchers/ramwatch &
~/.config/bspwm/watchers/batwatch &
~/.config/bspwm/watchers/swapwatch &
~/.config/bspwm/watchers/usbwatch &
~/.config/bspwm/watchers/volumewatch &
~/.config/bspwm/watchers/backlightwatch &

# Enable touchpad tapping
xinput set-prop "$(xinput list | grep Touchpad | grep -o 'id=[^[]*' | sed 's/[^0-9]*//g')" "libinput Tapping Enabled" 1 &
vibrant-cli eDP-1 1.3 &

# eye candies and some important stuff
xsetroot -cursor_name left_ptr &
feh --bg-fill ~/Pictures/Wallpapers/shiho.jpg
/usr/lib/polkit-kde-authentication-agent-1 &
dunst &
/usr/bin/kdeconnectd &
