backend = "glx"
vsync = true

animations = true

animation-stiffness = 110
animation-window-mass = 0.4
animation-dampening = 12
animation-clamping = true

animation-for-open-window = "zoom"
animation-for-unmap-window = "zoom"

blur-background = true
blur-method = "dual_kawase"
blur-strength = 3

corner-radius = 0

blur-include = [
    "class_g = 'Alacritty'"
]
