#!/bin/sh

get_bat_status() {
    cat /sys/class/power_supply/$1/status

}

BAT_DEV="BAT0"
LOCK=0
CHARGE_LOCK=0

while true; do

    status="$(get_bat_status $BAT_DEV)"

    if ! [ "$status" = "Charging" ]; then

        CHARGE_LOCK=0
        capacity="$(cat /sys/class/power_supply/$BAT_DEV/capacity)"
        echo $LOCK

        if [ $capacity -le 3 ] && ! [ $LOCK -ge 3 ]; then
            notify-send 'SYSTEM NOTICE' "Battery is basically non-existent. Shutting down in 1 minute"
            LOCK=3
            sleep 60
            current_status="$(get_bat_status $BAT_DEV)"
            [ "$current_status" = "Discharging" ] && systemctl poweroff || continue

        elif [ $capacity -le 10 ] && ! [ $LOCK -ge 2 ]; then
            notify-send 'SYSTEM NOTICE' "Battery is running very low: ${capacity}%"
            LOCK=2

        elif [ $capacity -le 20 ] && ! [ $LOCK -ge 1 ]; then
            notify-send 'SYSTEM NOTICE' "Battery is running low: ${capacity}%"
            LOCK=1

        elif [ $capacity -gt 20 ]; then
            LOCK=0

        fi

    elif [ "$status" = "Charging" ]; then
        CHARGE_LOCK=1

    fi

    sleep 1

done
