#!/bin/sh

# kernel error message baseline. some modules doesnt actually throw a real error (e.g when nvidia module is loading) and the order of some "error" messages are different

journalctl --no-pager -k -f -p 0..3 -o cat --output-fields="MESSAGE" | while read -r _; do

   notify-send -u critical "SYSTEM MALFUNCTION DETECTED"

done
