#!/bin/sh

LAST=""

while true; do

    current="$(playerctl metadata --format '{{artist}} - {{title}}' 2> /dev/null)"
    length=$(printf "$current" | wc -c)
    printf "$length\n"

    if [ "$current" != "$LAST" ] && ! [ "$length" -le 3 ]; then

        art="$(playerctl metadata mpris:artUrl 2> /dev/null)"
        ! [ $? -ge 1 ] && sleep 0.1

        notify-send "SYSTEM NOTICE" "Now playing: $current" -i "$art"
        LAST="$current"

    fi

    sleep 1

done
