#!/bin/sh

LAST=""

while true; do

    current="$(playerctl metadata --format '{{artist}} - {{title}}' 2> /dev/null)"
    sleep 0.1

    if [ -n "$current" ] && [ "$current" != "$LAST" ] && ! [ "$(printf $current | wc -c)" -eq 4 ]; then
        art="$(playerctl metadata mpris:artUrl 2> /dev/null)"

        ! [ $? -ge 1 ] && notify-send "SYSTEM NOTICE" "Now playing: $current" -i "$art"
        LAST="$current"

    fi

    sleep 1

done
