#!/bin/sh

# A lock to prevent notification spam
LOCK=0

while true; do
    used_ram=$(free -g | grep Mem | awk '{print $3}' | sed 's/[A-Za-z]*//g')

    if [ $used_ram -ge 4 ] && [ $LOCK -eq 0 ]; then
        LOCK=1
        notify-send -u normal 'SYSTEM NOTICE' 'Your computer RAM is running on single channel mode. System performance might be reduced'

    elif [ $used_ram -lt 4 ] && [ $LOCK -eq 1 ]; then
        LOCK=0

    fi

    sleep 5

done


