HISTFILE=~/.zsh_history
HISTSIZE=1000
SAVEHIST=1000
setopt autocd
setopt appendhistory

emulate sh -c '. /data/data/com.termux/files/usr/etc/profile'

command_not_found_handler() {
	/data/data/com.termux/files/usr/libexec/termux/command-not-found $1
}

preexec() {
	printf "\n"
}

bindkey "^[[H" beginning-of-line
bindkey "^[[F" end-of-line
bindkey "^[[5~" backward-word
bindkey "^[[6~" forward-word

alias ls='eza --icons --color=auto'
alias ll='ls -lh'
alias cte='chmod 755'
alias grep='grep --color=auto'

source /data/data/com.termux/files/usr/share/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

PROMPT=$'\n%F{#33275e}%K{#ccbeff} \uf015 %n@%M %f%k%F{#ccbeff}%K{#eeb8cb}\ue0bc%f%k%F{#492534}%K{#eeb8cb} \uf4d3 %(4~|.../%3~|%~) %f%k%F{#eeb8cb}\ue0bc%f\n%F{000}%K{255} %% %f%k%F{255}\ue0b0%f '
#PS1='%% '
# vim: set noet ft=zsh tw=4 sw=4 ff=unix
