#!/bin/sh
# This code has race conditions but it works good enough

if [ -f /tmp/health_stat_lock ]; then
    eww -c $HOME/.config/eww/main_widget close health-window
    rm /tmp/health_stat_lock
    exit 0

fi

eww -c $HOME/.config/eww/main_widget open health-window
touch /tmp/health_stat_lock
sleep 4
rm /tmp/health_stat_lock
eww -c $HOME/.config/eww/main_widget close health-window


