#!/bin/sh
# This code has race conditions but it works good enough

if [ -f /tmp/battery_stat_lock ]; then
    eww close battery-window
    rm /tmp/battery_stat_lock
    exit 0

fi

eww open bat-window
touch /tmp/battery_stat_lock
sleep 2
rm /tmp/battery_stat_lock
eww close bat-window


