#!/bin/sh
# This code has race conditions but it works good enough

if [ -f /tmp/music_stat_lock ]; then
    eww close music-window
    rm /tmp/music_stat_lock
    exit 0

fi

eww open music-window
touch /tmp/music_stat_lock
sleep 2
rm /tmp/music_stat_lock
eww close music-window


