# Material You
foreground=#F4EFF7
background=#1D1B1E
cursor=#F4EFF7

color0=#48454E
color1=#FFB4AB
color2=#B1D18A
color3=#EEB8CB
color4=#CCBEFF
color5=#F4B8E4
color6=#CAC3DC
color7=#F4EFF7

color8=#938F99
color9=#FFB4AB
color10=#B1D18A
color11=#EEB8CB
color12=#CCBEFF
color13=#F4B8E4
color14=#CAC3DC
color15=#F4EFF7
